/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.samsung.myapp;

public class ___MyThread___JNI {
  public final static native void MyThread_quit_set(long jarg1, MyThread jarg1_, boolean jarg2);
  public final static native boolean MyThread_quit_get(long jarg1, MyThread jarg1_);
  public final static native void MyThread_onPause(long jarg1, MyThread jarg1_);
  public final static native void MyThread_onResume(long jarg1, MyThread jarg1_);
  public final static native long new_MyThread();
  public final static native void delete_MyThread(long jarg1);
}
