/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.samsung.myapp;

public class __OpenGlSurface__ {
  public static void onSurfaceCreated() {
    __OpenGlSurface__JNI.onSurfaceCreated();
  }

  public static void onSurfaceChanged(int width, int height) {
    __OpenGlSurface__JNI.onSurfaceChanged(width, height);
  }

  public static void onDrawFrame() {
    __OpenGlSurface__JNI.onDrawFrame();
  }

}
