/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.samsung.myapp;

public class __OpenGlSurface__JNI {
  public final static native void onSurfaceCreated();
  public final static native void onSurfaceChanged(int jarg1, int jarg2);
  public final static native void onDrawFrame();
}
