/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.samsung.myapp;

public class MyThread {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public MyThread(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MyThread obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ___MyThread___JNI.delete_MyThread(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuit(boolean value) {
    ___MyThread___JNI.MyThread_quit_set(swigCPtr, this, value);
  }

  public boolean getQuit() {
    return ___MyThread___JNI.MyThread_quit_get(swigCPtr, this);
  }

  public void onPause() {
    ___MyThread___JNI.MyThread_onPause(swigCPtr, this);
  }

  public void onResume() {
    ___MyThread___JNI.MyThread_onResume(swigCPtr, this);
  }

  public MyThread() {
    this(___MyThread___JNI.new_MyThread(), true);
  }

}
